/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * READ-ONLY LLM CONTEXT - Do not edit this file.
 *
 * JSON File: agentcore/aws-targets.json
 * Purpose: AWS deployment targets for AgentCore resources
 */

// ─────────────────────────────────────────────────────────────────────────────
// ROOT SCHEMA: AwsDeploymentTargets (array)
// ─────────────────────────────────────────────────────────────────────────────

// The JSON file contains an array of deployment targets.
// Target names must be unique within the array.
type AwsDeploymentTargets = AwsDeploymentTarget[];

interface AwsDeploymentTarget {
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9_-]*$ @max 64 - unique identifier
  description?: string; // @max 256
  account: string; // @regex ^[0-9]{12}$ - AWS account ID (exactly 12 digits)
  region: AgentCoreRegion;
}

// ─────────────────────────────────────────────────────────────────────────────
// SUPPORTED REGIONS
// ─────────────────────────────────────────────────────────────────────────────

type AgentCoreRegion =
  | 'ap-northeast-1'
  | 'ap-south-1'
  | 'ap-southeast-1'
  | 'ap-southeast-2'
  | 'eu-central-1'
  | 'eu-west-1'
  | 'us-east-1'
  | 'us-east-2'
  | 'us-west-2';
